dbt_transparencia:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "{{ env_var('AZURE_SQL_DRIVER', 'ODBC Driver 17 for SQL Server') }}"
      server: "{{ env_var('AZURE_SQL_SERVER') }}"
      port: 1433
      database: "{{ env_var('AZURE_SQL_DATABASE') }}"
      schema: dbo
      user: "{{ env_var('AZURE_SQL_USER') }}"
      password: "{{ env_var('AZURE_SQL_PASSWORD') }}"
      trust_cert: false
      threads: 4