version: 2

models:
  - name: stg_cpgf_despesas
    columns:
      - name: id_transacao
        tests:
          - unique
          - not_null

  - name: dim_data
    description: "Dimensão Calendário/Tempo."
    columns:
      - name: sk_data
        tests:
          - unique
          - not_null

  - name: dim_orgaos
    description: "Dimensão de Órgãos Públicos e Unidades Gestoras."
    columns:
      - name: sk_orgao
        tests:
          - unique
          - not_null

  - name: dim_favorecidos
    description: "Dimensão de Estabelecimentos Comerciais e Fornecedores."
    columns:
      - name: sk_favorecido
        tests:
          - unique
          - not_null

  - name: dim_portadores
    description: "Dimensão de Portadores do Cartão Corporativo."
    columns:
      - name: sk_portador
        tests:
          - unique
          - not_null

  - name: fct_gastos_cartao
    description: "Tabela Fato transacional de despesas (Star Schema)."
    columns:
      - name: id_transacao
        tests:
          - unique
          - not_null
      - name: vl_transacao
        tests:
          - not_null
      - name: sk_data
        tests:
          - not_null
          - relationships:
              to: ref('dim_data')
              field: sk_data
      - name: sk_orgao
        tests:
          - not_null
          - relationships:
              to: ref('dim_orgaos')
              field: sk_orgao
      - name: sk_favorecido
        tests:
          - not_null
          - relationships:
              to: ref('dim_favorecidos')
              field: sk_favorecido
      - name: sk_portador
        tests:
          - not_null
          - relationships:
              to: ref('dim_portadores')
              field: sk_portador